# Generated by Django 4.0.6 on 2022-09-10 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sub_body', models.CharField(max_length=1000)),
                ('body', models.TextField()),
            ],
        ),
    ]
