# Generated by Django 4.0.6 on 2022-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0002_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=300, null='true'),
            preserve_default='true',
        ),
    ]
