# Generated by Django 4.0.6 on 2022-09-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0003_content_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='mod_faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
