# Generated by Django 4.0.6 on 2022-09-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0004_mod_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='com_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='better.front')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
