# Generated by Django 4.0.6 on 2022-09-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0005_com_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='com_section',
            old_name='post',
            new_name='grace',
        ),
    ]
